### ISSUE TITLE
Number of significant digits

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#5]
Results are shown with more digits than what is really relevant. 
e.g.  
Ee,lc	   807.000	mW/m²
correct would be 807.312 
maybe this comes because my data is in mW/nm, therefore the results are magnified by a factor of 1000.
But this looks like data is rounded to full W/m²

**Comment by DieterLa** [comment]
For the M-cone, the result is 719,8, but is rounded to 720. This is not nice. 
Accuracy should be better.

**Comment by JZauner** [comment]
So, this covers several topics. 

- One is importing. As I said in #4 , the data is supposed to be in W/m²*nm and needs to be scaled within the import options if it is not. So your data will be 807 W/m² instead of mW/m² if you did not scale it. Giving the option as part of #4 will hopefully make this clearer

- One is wanted rounding. What it does is show 0 decimals for values above 100, 1 decimal for values between 10 and 100, 2 decimals between 1 and 10, and 3 decimals below 1. Looking through many spectral measurements this seemed like a good balance between exact values and nice table formatting. I realize that I need to let people know of this rounding schema, and ideally let them opt out of it to get more exact numbers. You can already get the unrounded values through the Excel-Export.

- One is unwanted rounding, so a bug :). It rounds to three significant values, which is very much undesirable above values of 1000, so I need to fix this.

**Comment by JZauner** [comment]
Fixed the bug. It will go online in Version 1.0.0 of Spectran
